export const USER_UPDATE = 'user/USER_UPDATE';

export const USER_UPDATED = 'user/USER_UPDATED';

export const AUTHENTICATING = 'user/AUTHENTICATING';

export const AUTHENTICATE_WITH_CREDENTIAL = 'user/AUTHENTICATE_WITH_CREDENTIAL';

export const AUTH_FAILED = 'user/AUTH_FAILED';

export const USER_UPDATE_PRESENCE = 'user/USER_UPDATE_PRESENCE';

export const USER_UPDATE_ACTIVE_ROUTE = 'user/USER_UPDATE_ACTIVE_ROUTE';

export const TEMP_USER_UPDATE = 'user/TEMP_USER_UPDATE';

export const PICK_USER_BY_ID_PHONE = 'user/PICK_USER_BY_ID_PHONE';

export const SET_USER_BY_ID_PHONE = 'user/SET_USER_BY_ID_PHONE';

export const UPDATE_USER_LAST_ASKED_REVIEW_TIME =
  'user/UPDATE_USER_LAST_ASKED_REVIEW_TIME';
