export enum AppAuthProvider {
  GOOGLE = 'GOOGLE',
  APPLE = 'APPLE',
  FACEBOOK = 'FACEBOOK',
  EMAIL_PASSWORD_SIGN_IN = 'EMAIL_PASSWORD_SIGN_IN',
  EMAIL_PASSWORD_SIGN_UP = 'EMAIL_PASSWORD_SIGN_UP',
}
