import { SELF_EMPLOYED_DISPLAYED_NAME_PREFIX } from '$configs';

export const SOCIAL_SECURITY_ID_MASK = '999 999 999 99';
export const SOCIAL_SECURITY_ID_PLACEHOLDER = '000 000 000 00';
export const DISPLAYED_NAME_PLACEHOLDER =
  SELF_EMPLOYED_DISPLAYED_NAME_PREFIX.concat('Name');
