import { INDIVIDUAL_DISPLAYED_NAME_PREFIX } from '$configs';

export const SOCIAL_SECURITY_ID_MASK = '999 999 999 99';
export const SOCIAL_SECURITY_ID_PLACEHOLDER = '000 000 000 00';
export const DISPLAYED_NAME_PLACEHOLDER =
  INDIVIDUAL_DISPLAYED_NAME_PREFIX.concat('Name');

export const BIRTH_DATE_MASK = 'dd.MM.yyyy';
export const BIRTH_DATE_INPUT_PLACEHOLDER = 'DD.MM.YYYY';
